name: Snowflake Deployment

on:
  push:
    branches:
      - main
      - dev
      - 'feature/*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Snowflake CLI
        run: |
          pip install snowflake-cli-labs

      - name: Run SnowSQL
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_NAME }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          snowsql -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -p $SNOWFLAKE_PASSWORD << EOF
          USE WAREHOUSE HM_X_SMALL;
          USE ROLE SYSADMIN;
          SHOW USERS;
          SELECT * FROM SNOWGIT.SILVER.CUSTOMERS;
          EOF