name: Snowflake Deployment

on:
  push:
    branches:
      - main
      - dev
      - 'feature/*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install SnowSQL
        run: |
          curl -O https://s3.amazonaws.com/snowflake/software/snowsql/1.2/snowsql_1.2.16_linux_x86_64.sh
          chmod +x snowsql_1.2.16_linux_x86_64.sh
          ./snowsql_1.2.16_linux_x86_64.sh
          echo "export PATH=$PATH:$HOME/snowsql" >> $GITHUB_ENV
  
      - name: Configure Snowflake
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_NAME }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          snowsql -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -p $SNOWFLAKE_PASSWORD
          USE WAREHOUSE HM_X_SMALL;
          USE ROLE SYSADMIN;
          SHOW USERS;
          select * from SNOWGIT.SILVER.CUSTOMERS;
